# Include tasks for creating ddclient
- name: Install ddclient
  ansible.builtin.include_tasks: "install.yml"
  when: run_mode == "install"

- name: Uninstall ddclient
  ansible.builtin.include_tasks: "uninstall.yml"
  when: run_mode == "uninstall"
