# Include tasks for creating WUD
# https://getwud.github.io/wud/#/
- name: Install wud
  ansible.builtin.include_tasks: "install.yml"
  when: run_mode == "install"

- name: Uninstall wud
  ansible.builtin.include_tasks: "uninstall.yml"
  when: run_mode == "uninstall"
