# Stop and remove the ouroboros docker container
- name: Stop and Remove Docker Container - ouroboros
  community.docker.docker_container:
    state: absent
    name: ouroboros

# - name: Remove Docker Network - ouroboros-public
#   community.docker.docker_network:
#     state: absent
#     name: ouroboros-public
