# Stop and remove the watchtower docker container
- name: Stop and Remove Docker Container - watchtower
  community.docker.docker_container:
    state: absent
    name: watchtower

# - name: Remove Docker Network - watchtower-public
#   community.docker.docker_network:
#     state: absent
#     name: watchtower-public
