# Include tasks for creating btrbk backups
- name: Install btrbk
  ansible.builtin.include_tasks: "install.yml"
  when: run_mode == "install"

- name: Uninstall btrbk
  ansible.builtin.include_tasks: "uninstall.yml"
  when: run_mode == "uninstall"
